apiVersion: v1
kind: Service
metadata:
  name: codebase-wiki-postgres
  namespace: wiki-team
  labels:
    app: codebase-wiki-postgres
spec:
  type: ClusterIP
  selector:
    app: codebase-wiki-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
