apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codebase-wiki-postgres-data
  namespace: wiki-team
  labels:
    app: codebase-wiki-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
